// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSSAIzer.Backend.Db;

#nullable disable

namespace RSSAIzer.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250309194116_Steps")]
    partial class Steps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("RSSAIzer.Backend.Database.ChannelEntity", b =>
                {
                    b.Property<string>("TgId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("TgId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Channels", (string)null);
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.DigestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Digests", (string)null);
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.DigestStepEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DigestId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DigestId");

                    b.HasIndex("Type");

                    b.ToTable("DigestStatuses", (string)null);

                    b.HasDiscriminator<string>("EntityType").HasValue("DigestStepEntity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.DigestSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("AverageImportance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateTo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PostsCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PostsSummary")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DigestSummaries", (string)null);
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.PostSummaryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelTgId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DigestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importance")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelTgId");

                    b.HasIndex("DigestId");

                    b.ToTable("PostSummaries", (string)null);
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.AiProcessingStepEntity", b =>
                {
                    b.HasBaseType("RSSAIzer.Backend.Database.DigestStepEntity");

                    b.Property<int>("Percentage")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("AiProcessing");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.ErrorStepEntity", b =>
                {
                    b.HasBaseType("RSSAIzer.Backend.Database.DigestStepEntity");

                    b.Property<string>("ErrorsJsonSerialized")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionJsonSerialized")
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Error");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.RssReadingFinishedStepEntity", b =>
                {
                    b.HasBaseType("RSSAIzer.Backend.Database.DigestStepEntity");

                    b.Property<int>("PostsFound")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("RssReadingFinished");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.RssReadingStartedStepEntity", b =>
                {
                    b.HasBaseType("RSSAIzer.Backend.Database.DigestStepEntity");

                    b.Property<string>("ChannelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("RssReadingStarted");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.SimpleStepEntity", b =>
                {
                    b.HasBaseType("RSSAIzer.Backend.Database.DigestStepEntity");

                    b.HasDiscriminator().HasValue("Simple");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.DigestSummaryEntity", b =>
                {
                    b.HasOne("RSSAIzer.Backend.Database.DigestEntity", "DigestNav")
                        .WithOne("SummaryNav")
                        .HasForeignKey("RSSAIzer.Backend.Database.DigestSummaryEntity", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DigestNav");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.PostSummaryEntity", b =>
                {
                    b.HasOne("RSSAIzer.Backend.Database.ChannelEntity", "ChannelNav")
                        .WithMany()
                        .HasForeignKey("ChannelTgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RSSAIzer.Backend.Database.DigestEntity", "DigestNav")
                        .WithMany("PostsNav")
                        .HasForeignKey("DigestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChannelNav");

                    b.Navigation("DigestNav");
                });

            modelBuilder.Entity("RSSAIzer.Backend.Database.DigestEntity", b =>
                {
                    b.Navigation("PostsNav");

                    b.Navigation("SummaryNav");
                });
#pragma warning restore 612, 618
        }
    }
}
